FROM node:18-alpine

ARG VITE_DIGITRANSIT_SUBSCRIPTION_KEY=${VITE_DIGITRANSIT_SUBSCRIPTION_KEY}
ARG VITE_MAPBOX_ACCESS_TOKEN=${VITE_MAPBOX_ACCESS_TOKEN}

ENV VITE_DIGITRANSIT_SUBSCRIPTION_KEY=${VITE_DIGITRANSIT_SUBSCRIPTION_KEY}
ENV VITE_MAPBOX_ACCESS_TOKEN=${VITE_MAPBOX_ACCESS_TOKEN}


WORKDIR /app

COPY package.json .

RUN npm install

RUN npm i -g serve

COPY . .

RUN VITE_MAPBOX_ACCESS_TOKEN=${VITE_MAPBOX_ACCESS_TOKEN} VITE_DIGITRANSIT_SUBSCRIPTION_KEY=${VITE_DIGITRANSIT_SUBSCRIPTION_KEY} npm run build

EXPOSE 3000

CMD [ "serve", "-s", "dist" ]